-- create tables
create table ap1_approvazione (
    id                             number generated by default on null as identity 
                                   constraint ap1_approvazione_id_pk primary key,
    nome                           varchar2(255 char)
                                   constraint ap1_approvazione_nome_unq unique not null,
    email                          varchar2(255 char)
                                   constraint ap1_approvazione_email_unq unique not null,
    livello                        number default on null '1' not null
)
;

-- load data
insert into ap1_approvazione (nome,email,livello) values ('ROBERTO', 'roberto@capancioni.com', 1);
insert into ap1_approvazione (nome,email,livello) values ('MARIA', 'maria@capancioni.com', 1);
insert into ap1_approvazione (nome,email,livello) values ('FRANCO', 'franco@capancioni.com', 2);
insert into ap1_approvazione (nome,email,livello) values ('LUISA', 'luisa@capancioni.com', 2);
insert into ap1_approvazione (nome,email,livello) values ('CARLA', 'carla@capancioni.com', 3); 
-- Generated by Quick SQL Friday November 17, 2023  06:16:52
 
/*
approvazione
  nome vc255 /nn /unique
  email vc255 /nn /unique
  livello num /nn /default 1

# settings = { prefix: "AP1", semantics: "CHAR", language: "EN", APEX: true }
*/
